import type { Metadata } from "next";
import localFont from "next/font/local";
import { DarkModeProvider } from '../context/DarkModeContext';
import "./globals.css";
import DarkModeToggle from '../components/DarkModeToggle'; // Import the darkmode comoonent
import Link from "next/link"; // link from next for navigation

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Showcase SERL Projects",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DarkModeProvider>
          {/* Navigation bar */}
          <nav className="flex justify-between items-center p-4 bg-white dark:bg-black shadow-md">
            <div className="text-xl font-bold text-black dark:text-white">
              <Link href="/">Showcase SERL</Link>
            </div>
            <div className="flex items-center">
              <Link href="/" className="mx-2 text-black dark:text-white">Home</Link>
              <Link href="/projects" className="mx-2 text-black dark:text-white">Projects</Link>
              <Link href="/Kiosk" className="mx-2 text-black dark:text-white">Kiosk</Link>
              <DarkModeToggle /> {/* Dark mode toggle button */}
            </div>
          </nav>
          <main className="p-4">
            {children}
          </main>
        </DarkModeProvider>
      </body>
    </html>
  );
}
